# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8feb0b518379070d1c00eef40c42c08a4b9ca6edf23e98b5892783f3d8601d1cc1876d8e0e8573869cb482f1aa24853b961fae04b9c784b4c0f789343834cf5c

test:
  secret_key_base: 36491efa0803798ac1f747fdc1d5f240d6a2f760eff7be74423890409e91649825f5f2b43a941a60b385515322c601bca8d8a5533d6d30bb1b4d194a472f72d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
